export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_DONE = "API_CALL_DONE";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const CLEAR_INPUT_FIELDS = "CLEAR_INPUT_FIELDS";
export const GET_EMPLOYEE_DATA = "GET_EMPLOYEE_DATA";
export const ONBOARD_NEW_EMPLOYEE = "ONBOARD_NEW_EMPLOYEE";
